export {default as Addgame} from './addgame/Addgame'
export {default as BookingList} from './bookinglist/BookingList'
export {default as BookingDetails} from './bookingdetails/BookingDetails'
export {default as GameDetails} from './gamedetails/GameDetails'
export {default as Canteen} from './canteen/Canteen'