export {default as Banner} from './banner/Banner'
export {default as Contactform} from './contactform/Contactform'
export {default as Footer} from './Footer/Footer'
export {default as Navbar} from './navbar/Navbar'
export {default as Homepage} from './Homepage'
