export {default as Banner} from './banner/Banner'
export {default as Contactform} from './contactform/Contactform'
export {default as Footer} from './Footer/Footer'
export {default as Navigationbar} from './navbar/Navigationbar'
export {default as Homepage} from './Homepage'
